In [60]:
import numpy as np # type: ignore

In [61]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [62]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [63]:
# ------arange-----

In [64]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [71]:
# LİNSPACE böler ve aralarındaki mesafeleri eşit tutar. !! ÖNEMLİ !!

In [72]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [73]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
# RANDOM NUMPY DİZİSİ DÖNDÜRÜR.

In [77]:
np.random.randn(8)

array([-0.33959331, -1.21903814,  0.90027042,  0.87707336,  1.32544549,
       -0.27527023, -1.17675605, -0.14142242])

In [78]:
np.random.randn(4,4) #matrix yaptık

array([[-0.75932889,  1.54600655,  0.59435782,  0.30284974],
       [-0.56567999, -1.64252737,  0.27272637,  1.19890452],
       [ 0.12805364,  1.13144855,  1.08193993, -0.15452427],
       [-0.03478041,  0.72465747,  1.18915464,  0.40628087]])

In [79]:
np.random.randint(1,10) # 1 değer döndürür.son yazılan değer dönmez ama 1 döner

2

In [80]:
np.random.randint(1,10,5) # 1 ile 10 arasında 10 dahil değil 5 rakam döner.

array([3, 4, 7, 8, 8], dtype=int32)

In [81]:
np.random.randint(1,300,5)

array([  2,  97, 100, 149, 133], dtype=int32)

In [82]:
benimNumpyDizim = np.arange(30)

In [83]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
benimRandomDizim = np.random.randint(0,300,30)

In [85]:
benimRandomDizim

array([189,   9, 130,  21,  54,   2, 117,  84, 144, 208, 297, 295, 196,
        76, 161, 259,  11,  71, 183,  68, 280, 177, 126, 181,  57, 117,
        28, 299,   2,  70], dtype=int32)

NUMPY ARRAY METHODS

In [86]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [87]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [88]:
benimNumpyDizim.max()

np.int64(29)

In [89]:
benimRandomDizim.max()

np.int32(299)

In [90]:
benimRandomDizim.min()

np.int32(2)

In [91]:
benimRandomDizim.argmax()

np.int64(27)

In [92]:
benimRandomDizim.argmin()

np.int64(5)

In [93]:
benimNumpyDizim.shape

(30,)

In [94]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [95]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])